"""initial migration

Revision ID: 067db5716538
Revises: 
Create Date: 2025-10-21 19:21:12.514866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067db5716538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_modules',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('app_modules', schema=None) as batch_op:
        batch_op.create_index('ix_app_modules_sort', ['sort_order', 'code'], unique=False)

    op.create_table('branches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_ui_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_types',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('requires_expiry', sa.Boolean(), nullable=False),
    sa.Column('default_validity_days', sa.Integer(), nullable=True),
    sa.Column('remind_before_days', sa.Integer(), nullable=True),
    sa.Column('remind_every_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('field_schema', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_document_type_code')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('full_url', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('request_blob', sa.LargeBinary(), nullable=True),
    sa.Column('response_blob', sa.LargeBinary(), nullable=True),
    sa.Column('headers_blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('ix_issues_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_user_id'), ['user_id'], unique=False)

    op.create_table('national_holidays',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('deletable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('national_holidays', schema=None) as batch_op:
        batch_op.create_index('ix_holiday_date', ['holiday_date'], unique=False)

    op.create_table('permissions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name_en')
    )
    op.create_table('seed_registry',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('app_module_tabs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['app_modules.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'code', name='uq_module_tab_code')
    )
    with op.batch_alter_table('app_module_tabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_module_tabs_module_code'), ['module_code'], unique=False)
        batch_op.create_index('ix_module_tabs_sort', ['module_code', 'sort_order', 'code'], unique=False)

    op.create_table('employees',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('salary_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_employee_code'),
    sa.UniqueConstraint('email', name='uq_employee_email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employee_branch', ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_code'), ['code'], unique=True)

    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('employees_documents',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_expirable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notifications_muted', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.Date(), nullable=True),
    sa.Column('last_reminded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees_documents', schema=None) as batch_op:
        batch_op.create_index('ix_empdoc_doctype', ['document_type_id'], unique=False)
        batch_op.create_index('ix_empdoc_employee', ['employee_id'], unique=False)
        batch_op.create_index('ix_empdoc_expiry', ['expiry_date'], unique=False)

    op.create_table('notifications',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('object_table', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_object', ['object_table', 'object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('user_branches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_branches')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notifications_object')

    op.drop_table('notifications')
    with op.batch_alter_table('employees_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_empdoc_expiry')
        batch_op.drop_index('ix_empdoc_employee')
        batch_op.drop_index('ix_empdoc_doctype')

    op.drop_table('employees_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles_permissions')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_code'))
        batch_op.drop_index('ix_employee_branch')

    op.drop_table('employees')
    with op.batch_alter_table('app_module_tabs', schema=None) as batch_op:
        batch_op.drop_index('ix_module_tabs_sort')
        batch_op.drop_index(batch_op.f('ix_app_module_tabs_module_code'))

    op.drop_table('app_module_tabs')
    op.drop_table('seed_registry')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('national_holidays', schema=None) as batch_op:
        batch_op.drop_index('ix_holiday_date')

    op.drop_table('national_holidays')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_user_id'))
        batch_op.drop_index(batch_op.f('ix_issues_user_email'))
        batch_op.drop_index(batch_op.f('ix_issues_url'))
        batch_op.drop_index('ix_issues_status_created')

    op.drop_table('issues')
    op.drop_table('document_types')
    op.drop_table('branches')
    with op.batch_alter_table('app_modules', schema=None) as batch_op:
        batch_op.drop_index('ix_app_modules_sort')

    op.drop_table('app_modules')
    # ### end Alembic commands ###
