"""initial schema: update Employees

Revision ID: 1ca2e85a15c9
Revises: 3e20845aba82
Create Date: 2025-08-22 04:03:55.481480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca2e85a15c9'
down_revision = '3e20845aba82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_monthly', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nationality', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('meta')
        batch_op.drop_column('dob')
        batch_op.drop_column('nationality')
        batch_op.drop_column('salary_monthly')

    # ### end Alembic commands ###
