"""add modules tabs table

Revision ID: 379fbabcbc54
Revises: 775a230a5242
Create Date: 2025-08-31 00:01:58.702148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379fbabcbc54'
down_revision = '775a230a5242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_module_tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['app_modules.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'code', name='uq_module_tab_code')
    )
    with op.batch_alter_table('app_module_tabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_module_tabs_module_code'), ['module_code'], unique=False)
        batch_op.create_index('ix_module_tabs_sort', ['module_code', 'sort_order', 'code'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_object', ['object_table', 'object_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index('ix_notifications_object')

    with op.batch_alter_table('app_module_tabs', schema=None) as batch_op:
        batch_op.drop_index('ix_module_tabs_sort')
        batch_op.drop_index(batch_op.f('ix_app_module_tabs_module_code'))

    op.drop_table('app_module_tabs')
    # ### end Alembic commands ###
