"""add issues table

Revision ID: 775a230a5242
Revises: 1ca2e85a15c9
Create Date: 2025-08-29 16:51:14.111786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775a230a5242'
down_revision = '1ca2e85a15c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('full_url', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('request_blob', sa.LargeBinary(), nullable=True),
    sa.Column('response_blob', sa.LargeBinary(), nullable=True),
    sa.Column('headers_blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('ix_issues_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_user_id'))
        batch_op.drop_index(batch_op.f('ix_issues_user_email'))
        batch_op.drop_index(batch_op.f('ix_issues_url'))
        batch_op.drop_index('ix_issues_status_created')

    op.drop_table('issues')
    # ### end Alembic commands ###
