"""update modules tabs table

Revision ID: 89401ff1a26c
Revises: 379fbabcbc54
Create Date: 2025-09-14 23:33:55.719251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89401ff1a26c'
down_revision = '379fbabcbc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.create_index('ix_app_modules_sort', ['sort_order', 'code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_modules', schema=None) as batch_op:
        batch_op.drop_index('ix_app_modules_sort')
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
